FP='GGCAGCGTCAGATGTGTATAAGAGACAG';
RP='GCTCGGAGATTAGTTGCATAACC';
FPc=seqrcomplement(FP);
RPc=seqrcomplement(RP);
CIP='GGCAGCGTCAGATGTGTATAAGAGACAGNNNNNNNNNNGTCTACATCCCTGAGTCTATATGATGTAGATANNNNNNNNNNAAGGTTATGCAACTAATCTCCGAGCTAATATGATCACTAATGTCTGCATATAACTTACTCTAGGTATG';
CIPc=seqrcomplement(CIP);
CIPr='CTGTCTCTTATACACATCTGACGCTGCCCATACCTAGAGTAAGTTATATGCAGACATTAGTGATCATATTAGCTCGGAGATTAGTTGCATAACCTTNNNNNNNNNNTATCTACATCATATAGACTCAGGGATGTAGACNNNNNNNNNN';
%s=readAll('Reads');